# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5883684994f75668cb9bb807588f2967cf45fe1715cae0658f7413c3f14f1b7b602c4adef577d8efe3c59b28221217d6cd14f6f108395d30fbaeac4073b9079d

test:
  secret_key_base: 9517430e626bc9b5aa33d7cf3a2eede3ac28ef83dc327f4d54a29716a1f7d2a1d8da4e1cc3b5bbdb52e23f2f32a53f08fe11a34ad8dd53e0bfeba859daaef270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
